CREATE DATABASE learnsql;

USE learnsql;

DROP TABLE IF EXISTS employees;

create table employees (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	age INT,
	gender VARCHAR(50),
	dob DATE,
	city VARCHAR(9),
	salary VARCHAR(6),
	department VARCHAR(25)
);

insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (1, 'Annie', 'Langan', 41, 'Female', '2009/09/09', 'Delhi', 70000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (2, 'Maude', 'Stothart', 49, 'Female', '2002/06/09', 'Ahmedabad', 65000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (3, 'Delphinia', 'Elmhirst', 28, 'Agender', '2013/11/18', 'Bangalore', 35000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (4, 'Ulrick', 'Lembke', 46, 'Male', '2000/04/10', 'Chennai', 55000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (5, 'Margarethe', 'Dinjes', 30, 'Female', '2017/02/22', 'Chennai', 55000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (6, 'Amelia', 'Perkin', 40, 'Female', '2022/05/13', 'Pune', 55000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (7, 'Cariotta', 'Gaitone', 43, 'Female', '1993/06/09', 'Kolkata', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (8, 'Aloin', 'Farquhar', 44, 'Male', '2020/07/15', 'Surat', 70000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (9, 'Essy', 'Cardus', 49, 'Female', '2022/10/10', 'Pune', 50000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (10, 'Iona', 'Gutcher', 32, 'Female', '2007/05/28', 'Pune', 65000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (11, 'Armando', 'Pellamont', 52, 'Male', '1992/10/06', 'Surat', 45000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (12, 'Aland', 'Yemm', 49, 'Male', '2021/09/25', 'Kolkata', 90000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (13, 'Benjamin', 'Monsey', 54, 'Male', '2020/11/30', 'Delhi', 75000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (14, 'Ervin', 'Carnegie', 55, 'Male', '2013/06/15', 'Pune', 55000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (15, 'Nesta', 'Brislan', 36, 'Female', '1993/03/09', 'Ahmedabad', 70000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (16, 'Rufe', 'Ruddick', 53, 'Male', '2021/07/19', 'Pune', 45000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (17, 'Alexandre', 'Pretor', 34, 'Male', '1997/04/27', 'Hyderabad', 75000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (18, 'Chicky', 'Riste', 54, 'Female', '2018/03/24', 'Chennai', 95000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (19, 'Beatrisa', 'Burlingame', 27, 'Female', '2009/12/23', 'Surat', 75000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (20, 'Devon', 'Hourston', 31, 'Female', '1995/07/10', 'Jaipur', 50000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (21, 'Silva', 'Martschik', 35, 'Female', '2003/08/04', 'Bangalore', 90000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (22, 'Blondell', 'Angelo', 43, 'Female', '2008/03/31', 'Hyderabad', 50000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (23, 'Oralle', 'Alliband', 38, 'Female', '2012/03/04', 'Bangalore', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (24, 'Prissie', 'Baus', 53, 'Female', '2021/05/13', 'Bangalore', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (25, 'Tye', 'Freak', 51, 'Male', '2011/06/25', 'Ahmedabad', 55000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (26, 'Flynn', 'Synke', 52, 'Male', '2014/03/21', 'Chennai', 95000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (27, 'Janna', 'Williams', 34, 'Female', '2023/04/04', 'Chennai', 80000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (28, 'Mary', 'Fazakerley', 39, 'Female', '2015/07/27', 'Chennai', 75000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (29, 'Kass', 'Coultish', 28, 'Non-binary', '2000/09/02', 'Hyderabad', 95000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (30, 'Cristen', 'Deverill', 44, 'Female', '1998/06/30', 'Bangalore', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (31, 'Dewitt', 'Cuffley', 46, 'Male', '2013/11/29', 'Chennai', 40000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (32, 'Nathaniel', 'Gopsell', 45, 'Male', '2016/07/17', 'Pune', 80000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (33, 'Kevina', 'Meiklam', 34, 'Bigender', '2014/10/20', 'Bangalore', 100000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (34, 'Cathrine', 'Lenney', 43, 'Female', '2020/08/22', 'Chennai', 90000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (35, 'Gloria', 'Linfield', 32, 'Female', '2009/03/13', 'Ahmedabad', 90000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (36, 'Derick', 'Beyne', 40, 'Male', '1994/11/18', 'Chennai', 45000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (37, 'Nikita', 'Whitmore', 47, 'Male', '2017/09/01', 'Surat', 75000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (38, 'Nero', 'Ungerecht', 44, 'Male', '2011/08/09', 'Kolkata', 95000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (39, 'Wynnie', 'Plumley', 27, 'Female', '1999/11/20', 'Mumbai', 60000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (40, 'Ferguson', 'Grenshiels', 44, 'Male', '1999/09/06', 'Mumbai', 50000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (41, 'Mac', 'Maskrey', 50, 'Male', '2017/04/19', 'Surat', 55000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (42, 'Ronny', 'Lumsdon', 44, 'Female', '1997/10/12', 'Bangalore', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (43, 'Felipe', 'Yetts', 29, 'Male', '2018/06/29', 'Kolkata', 40000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (44, 'Worthy', 'Duffield', 51, 'Male', '2003/10/17', 'Chennai', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (45, 'Ranique', 'Stobie', 53, 'Female', '2002/04/02', 'Delhi', 35000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (46, 'Neysa', 'Cosbey', 30, 'Female', '1998/11/04', 'Delhi', 35000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (47, 'Godwin', 'Vahey', 27, 'Male', '2009/06/11', 'Mumbai', 95000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (48, 'Kendall', 'Bingham', 49, 'Male', '2003/09/07', 'Pune', 80000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (49, 'Dorelle', 'Faulkes', 34, 'Female', '2016/03/03', 'Kolkata', 60000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (50, 'Demetris', 'Glamart', 39, 'Female', '2017/11/12', 'Surat', 70000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (51, 'Terri', 'Geraldi', 27, 'Female', '2023/03/10', 'Hyderabad', 45000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (52, 'Marten', 'Galbreath', 30, 'Male', '2015/12/15', 'Surat', 35000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (53, 'Killy', 'Pressland', 31, 'Male', '2007/11/19', 'Delhi', 80000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (54, 'Brianna', 'Scholer', 55, 'Female', '2009/04/22', 'Jaipur', 50000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (55, 'Cate', 'Hargitt', 32, 'Female', '2000/03/20', 'Hyderabad', 85000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (56, 'Darell', 'Feldberg', 29, 'Female', '2020/02/26', 'Kolkata', 35000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (57, 'Madalyn', 'Jean', 44, 'Female', '2008/02/04', 'Surat', 90000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (58, 'Cathie', 'Dyment', 40, 'Female', '2005/02/23', 'Jaipur', 60000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (59, 'Wilone', 'Bowker', 41, 'Female', '2018/03/18', 'Delhi', 80000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (60, 'Rutledge', 'Rabbitts', 42, 'Male', '1998/07/05', 'Ahmedabad', 60000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (61, 'Yancey', 'Coveley', 34, 'Male', '1993/08/01', 'Delhi', 90000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (62, 'Sharl', 'Chellenham', 28, 'Female', '2008/08/24', 'Mumbai', 35000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (63, 'Mycah', 'Bogie', 37, 'Male', '2013/11/02', 'Surat', 75000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (64, 'Kirby', 'Bowmer', 39, 'Genderqueer', '2013/09/08', 'Surat', 80000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (65, 'Leia', 'Broschek', 32, 'Female', '2015/06/20', 'Bangalore', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (66, 'Roseline', 'Zanitti', 38, 'Female', '2015/01/24', 'Delhi', 60000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (67, 'Banky', 'Breed', 48, 'Male', '2021/03/13', 'Pune', 35000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (68, 'Britte', 'Bertl', 44, 'Female', '2012/05/04', 'Mumbai', 40000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (69, 'Kaspar', 'Daskiewicz', 30, 'Male', '1998/12/24', 'Mumbai', 45000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (70, 'Hammad', 'Archbutt', 28, 'Male', '2003/04/11', 'Kolkata', 75000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (71, 'Gardner', 'Anglish', 45, 'Male', '2004/03/16', 'Bangalore', 65000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (72, 'Grata', 'Corteney', 48, 'Female', '2014/11/14', 'Hyderabad', 85000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (73, 'Charmion', 'Floyed', 34, 'Female', '1993/05/31', 'Jaipur', 90000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (74, 'Zsazsa', 'Hewes', 33, 'Female', '2022/08/04', 'Kolkata', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (75, 'Torrence', 'Rooksby', 32, 'Male', '1996/07/01', 'Surat', 95000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (76, 'Kennith', 'Duffrie', 40, 'Male', '2000/12/29', 'Pune', 65000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (77, 'Leonhard', 'Duffit', 28, 'Male', '2005/05/10', 'Pune', 50000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (78, 'Donalt', 'Sharratt', 28, 'Male', '2005/05/19', 'Jaipur', 55000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (79, 'Corby', 'Gouly', 40, 'Male', '2009/08/31', 'Jaipur', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (80, 'Nevile', 'Bulman', 40, 'Male', '2000/10/23', 'Hyderabad', 65000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (81, 'Selie', 'Alison', 53, 'Female', '2006/02/19', 'Surat', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (82, 'Tawnya', 'Whitten', 51, 'Polygender', '1998/02/25', 'Hyderabad', 40000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (83, 'Nerte', 'Axelbee', 49, 'Female', '1997/04/25', 'Jaipur', 50000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (84, 'Eberhard', 'Duncanson', 34, 'Male', '1993/04/14', 'Delhi', 90000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (85, 'Nathalie', 'Tallet', 53, 'Female', '2019/07/09', 'Delhi', 60000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (86, 'Cecilio', 'Benettelli', 36, 'Male', '2021/01/01', 'Chennai', 85000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (87, 'Shelba', 'Erwin', 37, 'Female', '2020/03/25', 'Surat', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (88, 'Vivianna', 'Lightfoot', 36, 'Female', '2021/09/27', 'Kolkata', 35000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (89, 'Tiffie', 'McKeag', 30, 'Female', '1998/07/24', 'Ahmedabad', 50000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (90, 'Binny', 'Postle', 41, 'Female', '2008/02/26', 'Mumbai', 100000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (91, 'Ellsworth', 'Guiu', 54, 'Male', '2009/02/21', 'Bangalore', 85000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (92, 'Rowena', 'Corneljes', 50, 'Female', '2020/01/07', 'Bangalore', 55000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (93, 'Paige', 'Vayro', 30, 'Bigender', '2000/07/13', 'Jaipur', 80000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (94, 'Haydon', 'Berntsson', 39, 'Male', '2006/11/10', 'Mumbai', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (95, 'Ianthe', 'Aubrey', 43, 'Bigender', '2021/03/29', 'Chennai', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (96, 'Melony', 'Fishly', 50, 'Female', '2002/08/07', 'Chennai', 40000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (97, 'Ken', 'Preator', 35, 'Male', '2005/10/17', 'Bangalore', 75000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (98, 'Thaxter', 'Grunwall', 36, 'Male', '2015/10/23', 'Mumbai', 80000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (99, 'Biddy', 'Vondrasek', 28, 'Female', '2016/03/26', 'Surat', 40000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (100, 'Bale', 'Warratt', 32, 'Male', '2007/12/29', 'Hyderabad', 85000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (101, 'Stevie', 'Wisniewski', 45, 'Male', '2019/12/07', 'Hyderabad', 80000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (102, 'Raviv', 'Kidner', 38, 'Male', '1993/03/15', 'Mumbai', 45000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (103, 'Carr', 'Berthomieu', 48, 'Male', '2013/12/21', 'Ahmedabad', 100000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (104, 'Patrizius', 'Attewell', 36, 'Male', '1998/06/17', 'Delhi', 35000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (105, 'Laurence', 'Puffett', 37, 'Male', '1993/02/19', 'Ahmedabad', 75000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (106, 'Hettie', 'Pennycook', 39, 'Female', '1998/11/29', 'Surat', 70000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (107, 'Sibel', 'Bartles', 36, 'Female', '2012/02/19', 'Ahmedabad', 80000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (108, 'Anderea', 'Cockson', 46, 'Polygender', '2008/02/15', 'Kolkata', 80000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (109, 'Maynard', 'Nevitt', 53, 'Male', '2012/07/27', 'Chennai', 90000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (110, 'Tad', 'Symington', 52, 'Male', '2017/02/01', 'Mumbai', 35000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (111, 'Corrianne', 'Soppeth', 44, 'Female', '1997/12/20', 'Jaipur', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (112, 'Dallas', 'Bleddon', 48, 'Genderfluid', '2008/01/08', 'Hyderabad', 45000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (113, 'Dwain', 'Hurlestone', 32, 'Male', '2012/01/08', 'Kolkata', 75000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (114, 'Anetta', 'Stanlack', 39, 'Female', '2014/10/01', 'Surat', 40000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (115, 'Vito', 'Cosgrave', 43, 'Male', '2003/03/10', 'Jaipur', 100000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (116, 'Atalanta', 'Delucia', 45, 'Female', '2004/09/18', 'Bangalore', 50000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (117, 'Bo', 'Vallintine', 27, 'Male', '2018/09/14', 'Ahmedabad', 70000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (118, 'Kirbee', 'O''Reilly', 44, 'Female', '2018/11/23', 'Surat', 80000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (119, 'Tonya', 'McNerlin', 55, 'Female', '2013/05/03', 'Surat', 100000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (120, 'Eugenie', 'Corona', 40, 'Female', '1994/12/03', 'Surat', 60000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (121, 'Katalin', 'McLardie', 43, 'Female', '2011/04/10', 'Jaipur', 40000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (122, 'Clevey', 'Stonbridge', 48, 'Male', '2014/08/13', 'Mumbai', 40000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (123, 'Bent', 'Pasticznyk', 45, 'Male', '2009/03/24', 'Chennai', 60000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (124, 'Parry', 'Mayte', 30, 'Male', '2020/09/16', 'Kolkata', 60000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (125, 'Dinah', 'Eddis', 39, 'Female', '2000/06/24', 'Hyderabad', 85000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (126, 'Benedetto', 'Ellerby', 35, 'Polygender', '2022/06/17', 'Ahmedabad', 45000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (127, 'Pietra', 'Blanche', 53, 'Female', '2003/01/12', 'Kolkata', 90000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (128, 'Fleurette', 'Bowstead', 40, 'Female', '2006/09/18', 'Mumbai', 55000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (129, 'Grantham', 'Tunnock', 29, 'Male', '2005/10/22', 'Jaipur', 45000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (130, 'Elysee', 'Dearness', 28, 'Female', '2006/04/21', 'Bangalore', 65000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (131, 'Shurlock', 'Carous', 51, 'Male', '2009/10/17', 'Hyderabad', 85000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (132, 'Shannon', 'Adamski', 29, 'Female', '2016/03/18', 'Kolkata', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (133, 'Harriet', 'Auden', 38, 'Female', '1994/07/14', 'Kolkata', 45000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (134, 'Gus', 'Godden', 53, 'Female', '1994/10/13', 'Kolkata', 40000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (135, 'Chilton', 'Dyer', 55, 'Male', '2015/11/07', 'Chennai', 85000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (136, 'Rey', 'Dumphries', 33, 'Male', '1996/10/07', 'Hyderabad', 65000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (137, 'Cathi', 'Maybey', 40, 'Female', '2018/10/27', 'Chennai', 70000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (138, 'Siffre', 'Huetson', 30, 'Male', '2010/03/15', 'Mumbai', 40000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (139, 'Codie', 'Rowler', 37, 'Bigender', '2013/05/10', 'Jaipur', 85000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (140, 'Monah', 'Hefner', 51, 'Female', '1998/07/24', 'Chennai', 50000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (141, 'Debby', 'D''Ruel', 55, 'Female', '2023/06/12', 'Bangalore', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (142, 'Trenna', 'Brand-Hardy', 53, 'Female', '1992/11/30', 'Kolkata', 65000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (143, 'Kayley', 'Wake', 46, 'Female', '1998/05/10', 'Ahmedabad', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (144, 'Jacobo', 'Mathonnet', 30, 'Male', '2005/01/23', 'Bangalore', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (145, 'Cristobal', 'Havercroft', 55, 'Male', '2015/07/04', 'Mumbai', 70000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (146, 'Natasha', 'Lewknor', 36, 'Female', '1996/10/22', 'Surat', 35000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (147, 'Homerus', 'MacNeill', 34, 'Male', '2019/04/28', 'Hyderabad', 95000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (148, 'Kaiser', 'Lisciardelli', 52, 'Male', '1995/08/01', 'Bangalore', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (149, 'Binky', 'Annes', 38, 'Male', '2019/07/09', 'Mumbai', 60000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (150, 'Clive', 'McLeish', 51, 'Male', '1999/12/05', 'Ahmedabad', 55000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (151, 'Danika', 'Stracey', 37, 'Agender', '1997/05/01', 'Jaipur', 85000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (152, 'Reyna', 'Precious', 33, 'Female', '2011/01/26', 'Chennai', 80000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (153, 'Eric', 'Vuitte', 34, 'Male', '1999/08/30', 'Delhi', 35000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (154, 'Bertina', 'Fist', 38, 'Female', '1994/06/20', 'Chennai', 45000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (155, 'Ahmad', 'Tessier', 35, 'Male', '2015/08/22', 'Delhi', 80000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (156, 'Scotti', 'Buten', 39, 'Male', '2012/04/16', 'Hyderabad', 70000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (157, 'Olag', 'Scollard', 51, 'Male', '2007/02/01', 'Jaipur', 80000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (158, 'Prinz', 'Danelet', 52, 'Male', '1994/08/25', 'Ahmedabad', 100000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (159, 'Drona', 'Patton', 38, 'Female', '2015/04/05', 'Chennai', 60000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (160, 'Homere', 'Burkinshaw', 48, 'Male', '2002/02/01', 'Ahmedabad', 95000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (161, 'Dudley', 'Doodney', 35, 'Genderqueer', '2006/04/07', 'Surat', 50000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (162, 'Joela', 'Weir', 29, 'Female', '2000/04/22', 'Mumbai', 50000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (163, 'Becka', 'Moro', 44, 'Female', '2005/12/15', 'Kolkata', 50000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (164, 'Gabriel', 'Mallia', 27, 'Male', '2003/01/15', 'Surat', 70000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (165, 'Veradis', 'Beange', 46, 'Female', '2021/02/13', 'Bangalore', 95000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (166, 'Theodor', 'Foxten', 47, 'Male', '2004/11/25', 'Jaipur', 100000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (167, 'Paxon', 'Brydone', 29, 'Male', '2013/05/17', 'Bangalore', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (168, 'Meta', 'Botcherby', 31, 'Genderfluid', '2007/07/09', 'Pune', 80000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (169, 'Haily', 'Pulford', 27, 'Female', '2013/06/20', 'Jaipur', 55000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (170, 'Dion', 'Kendle', 53, 'Female', '1998/08/28', 'Hyderabad', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (171, 'Storm', 'Bibb', 45, 'Female', '2004/10/05', 'Delhi', 55000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (172, 'Darell', 'Roblin', 32, 'Female', '2003/09/01', 'Surat', 85000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (173, 'Alene', 'Hattiff', 43, 'Female', '2004/01/23', 'Kolkata', 70000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (174, 'Paige', 'Mowday', 39, 'Male', '2015/04/30', 'Mumbai', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (175, 'Chrysler', 'Tibald', 33, 'Female', '2001/07/19', 'Bangalore', 70000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (176, 'Alisa', 'Preist', 38, 'Female', '2021/07/21', 'Pune', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (177, 'Felix', 'Wormald', 38, 'Male', '2001/05/07', 'Ahmedabad', 80000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (178, 'Griselda', 'Symcox', 47, 'Female', '2013/04/25', 'Chennai', 70000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (179, 'Rabi', 'Johnston', 40, 'Male', '2017/09/10', 'Ahmedabad', 60000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (180, 'Saw', 'Arnaudot', 34, 'Male', '1993/02/21', 'Pune', 75000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (181, 'Sara-ann', 'Sibthorpe', 31, 'Female', '2008/01/08', 'Ahmedabad', 100000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (182, 'Philipa', 'Coorington', 41, 'Female', '2017/09/23', 'Ahmedabad', 35000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (183, 'Corrie', 'Montfort', 38, 'Genderfluid', '1995/10/01', 'Bangalore', 35000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (184, 'Karin', 'Godlonton', 37, 'Female', '2018/02/13', 'Delhi', 95000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (185, 'Glenn', 'Lodo', 40, 'Male', '2011/12/15', 'Surat', 75000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (186, 'Breanne', 'Reinhart', 41, 'Female', '2014/06/10', 'Pune', 35000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (187, 'Stanton', 'Boosey', 30, 'Male', '2001/03/28', 'Pune', 95000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (188, 'Kylynn', 'Dugald', 55, 'Female', '2016/04/23', 'Jaipur', 100000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (189, 'Isador', 'Quail', 33, 'Male', '2017/12/17', 'Jaipur', 65000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (190, 'Shaina', 'Millership', 38, 'Female', '1995/01/08', 'Mumbai', 40000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (191, 'Teresita', 'Crutchfield', 33, 'Female', '2001/12/10', 'Hyderabad', 95000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (192, 'Cosetta', 'Atlay', 51, 'Female', '2007/10/10', 'Bangalore', 70000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (193, 'Anthiathia', 'O'' Hogan', 41, 'Female', '1996/02/10', 'Pune', 40000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (194, 'Gisela', 'Codlin', 49, 'Female', '2013/01/11', 'Kolkata', 40000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (195, 'Harland', 'Dorbin', 44, 'Male', '2007/10/30', 'Chennai', 65000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (196, 'Agna', 'Weaver', 34, 'Female', '1998/01/09', 'Surat', 90000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (197, 'Nelli', 'Garrood', 37, 'Female', '2008/07/16', 'Jaipur', 60000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (198, 'Wilhelmine', 'Barsam', 27, 'Female', '2019/05/13', 'Kolkata', 90000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (199, 'Adorne', 'Craisford', 37, 'Genderfluid', '2021/10/21', 'Bangalore', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (200, 'Ettore', 'Caustick', 54, 'Male', '1997/10/17', 'Surat', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (201, 'Staford', 'Bickerstaff', 27, 'Male', '1992/11/06', 'Bangalore', 55000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (202, 'Fonsie', 'Tue', 55, 'Non-binary', '2018/09/26', 'Pune', 85000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (203, 'Benedicto', 'Wilprecht', 52, 'Male', '2009/03/07', 'Bangalore', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (204, 'Cordie', 'Jolliff', 27, 'Male', '2016/09/17', 'Mumbai', 45000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (205, 'Kaela', 'Iacomelli', 37, 'Female', '1996/03/19', 'Surat', 40000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (206, 'Syman', 'Gryglewski', 38, 'Male', '1992/09/25', 'Chennai', 70000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (207, 'Vance', 'Kadwallider', 51, 'Male', '1997/05/05', 'Ahmedabad', 75000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (208, 'Raimund', 'Heeran', 38, 'Male', '1999/03/11', 'Bangalore', 80000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (209, 'Jeri', 'McTrustrie', 45, 'Female', '2003/09/06', 'Hyderabad', 65000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (210, 'Kingston', 'Apple', 47, 'Genderqueer', '1999/07/20', 'Pune', 95000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (211, 'Evelina', 'Buzek', 38, 'Genderfluid', '1998/10/25', 'Ahmedabad', 95000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (212, 'Obediah', 'Van der Velde', 31, 'Male', '2009/02/28', 'Pune', 70000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (213, 'Hedvige', 'Frederick', 53, 'Female', '2013/11/30', 'Chennai', 75000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (214, 'Sherwynd', 'Annett', 32, 'Male', '2021/03/21', 'Ahmedabad', 40000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (215, 'Sigismund', 'Marchington', 53, 'Male', '2013/12/10', 'Surat', 75000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (216, 'Wynn', 'Helleckas', 54, 'Female', '2009/05/21', 'Hyderabad', 80000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (217, 'Cecily', 'Nairns', 37, 'Female', '2022/07/29', 'Delhi', 75000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (218, 'Hettie', 'Lamb-shine', 37, 'Female', '1999/04/19', 'Pune', 55000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (219, 'Fredek', 'Wyke', 47, 'Male', '2003/11/16', 'Bangalore', 95000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (220, 'Fergus', 'Colvin', 44, 'Male', '2019/04/27', 'Jaipur', 35000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (221, 'Maggie', 'Lacasa', 41, 'Female', '2010/04/24', 'Delhi', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (222, 'Lorne', 'M''Quharg', 28, 'Male', '1997/01/19', 'Delhi', 50000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (223, 'Duffy', 'Winchurch', 31, 'Male', '2009/11/06', 'Delhi', 40000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (224, 'Clark', 'Tutchings', 29, 'Male', '2004/01/16', 'Delhi', 85000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (225, 'Felizio', 'Noyes', 44, 'Male', '1995/04/19', 'Chennai', 100000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (226, 'Bron', 'Huxstep', 49, 'Male', '2000/03/26', 'Pune', 40000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (227, 'Jack', 'Puffett', 42, 'Male', '1998/04/09', 'Delhi', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (228, 'Tilly', 'Gleader', 52, 'Female', '2016/12/30', 'Ahmedabad', 85000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (229, 'Isa', 'Nijs', 28, 'Female', '2006/12/12', 'Chennai', 55000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (230, 'Lauri', 'Simunek', 51, 'Female', '1998/01/31', 'Delhi', 80000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (231, 'Gib', 'Salthouse', 28, 'Male', '1998/01/17', 'Hyderabad', 95000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (232, 'Jacki', 'Blizard', 27, 'Female', '2014/04/28', 'Mumbai', 95000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (233, 'Benita', 'Reihm', 29, 'Polygender', '2003/02/27', 'Chennai', 45000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (234, 'Porty', 'Perot', 33, 'Male', '2005/06/14', 'Hyderabad', 50000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (235, 'Guillaume', 'Slipper', 38, 'Male', '2005/10/24', 'Ahmedabad', 90000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (236, 'Zebadiah', 'Stonhewer', 44, 'Male', '2018/06/29', 'Delhi', 75000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (237, 'Reggie', 'Quarmby', 39, 'Female', '2010/02/09', 'Chennai', 35000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (238, 'Ofelia', 'Bidmead', 37, 'Female', '2008/11/10', 'Surat', 90000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (239, 'Em', 'Swalwel', 32, 'Male', '2021/03/15', 'Kolkata', 100000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (240, 'Kathy', 'Simeoli', 46, 'Female', '2008/01/15', 'Mumbai', 80000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (241, 'Sidonia', 'Maywood', 36, 'Female', '1993/08/04', 'Surat', 45000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (242, 'Frederique', 'Hellin', 52, 'Female', '2003/01/29', 'Kolkata', 60000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (243, 'Sherrie', 'Kelemen', 33, 'Female', '2008/12/09', 'Jaipur', 35000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (244, 'Tersina', 'Gutch', 29, 'Female', '1997/02/08', 'Chennai', 65000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (245, 'Emile', 'Littlefair', 36, 'Male', '2014/01/09', 'Delhi', 45000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (246, 'Rubin', 'Wreford', 47, 'Male', '2020/03/07', 'Chennai', 50000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (247, 'Guthrey', 'Hearnshaw', 53, 'Male', '2002/11/13', 'Pune', 95000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (248, 'Morgana', 'Mongin', 50, 'Female', '2000/07/31', 'Delhi', 35000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (249, 'Farrah', 'Normavill', 42, 'Female', '2005/10/25', 'Hyderabad', 80000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (250, 'Stephanus', 'Lilie', 54, 'Male', '2016/02/26', 'Mumbai', 35000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (251, 'Morton', 'Cowles', 35, 'Male', '2005/09/30', 'Ahmedabad', 35000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (252, 'Wesley', 'Normavill', 54, 'Male', '2011/07/18', 'Bangalore', 75000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (253, 'Ly', 'Heffernon', 36, 'Male', '2012/10/29', 'Delhi', 70000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (254, 'Barnebas', 'Hutton', 44, 'Male', '2000/02/25', 'Mumbai', 55000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (255, 'Garvy', 'Leate', 36, 'Male', '1994/06/21', 'Ahmedabad', 80000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (256, 'Jarid', 'Southon', 33, 'Male', '2000/05/06', 'Kolkata', 35000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (257, 'Sibylle', 'Broggio', 34, 'Female', '2014/10/12', 'Hyderabad', 75000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (258, 'Aurore', 'Fowlds', 51, 'Bigender', '2003/02/22', 'Pune', 90000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (259, 'Alberta', 'Olexa', 51, 'Female', '1996/07/12', 'Jaipur', 75000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (260, 'Laurie', 'Kmietsch', 32, 'Female', '1999/12/12', 'Pune', 55000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (261, 'Elnore', 'Gonnard', 37, 'Female', '1992/07/14', 'Kolkata', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (262, 'Torry', 'Colliber', 41, 'Male', '2004/07/18', 'Jaipur', 85000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (263, 'Elly', 'Neely', 43, 'Female', '2001/04/30', 'Surat', 50000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (264, 'Halli', 'Spinelli', 42, 'Female', '2006/04/22', 'Jaipur', 75000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (265, 'James', 'Kebell', 38, 'Male', '2005/10/01', 'Pune', 85000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (266, 'Romain', 'Mullinger', 53, 'Male', '2023/06/07', 'Mumbai', 70000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (267, 'Emma', 'Tutt', 43, 'Female', '1993/10/05', 'Delhi', 50000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (268, 'Flory', 'Bassick', 53, 'Female', '2001/11/03', 'Surat', 40000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (269, 'Johna', 'Kasher', 46, 'Bigender', '2020/06/21', 'Bangalore', 35000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (270, 'Elysee', 'Heinssen', 29, 'Female', '2007/08/29', 'Bangalore', 85000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (271, 'Theresa', 'Wakley', 40, 'Female', '2006/08/17', 'Ahmedabad', 55000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (272, 'Yasmin', 'Downie', 46, 'Female', '2000/05/07', 'Bangalore', 85000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (273, 'Harman', 'Brecher', 45, 'Agender', '2006/08/22', 'Delhi', 80000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (274, 'Kelley', 'Hutchings', 27, 'Female', '1999/11/01', 'Kolkata', 55000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (275, 'Gracia', 'Bierling', 52, 'Female', '1999/09/22', 'Jaipur', 60000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (276, 'Perceval', 'Mcsarry', 48, 'Male', '2005/05/06', 'Bangalore', 50000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (277, 'Ware', 'Falkner', 35, 'Male', '1993/12/14', 'Jaipur', 90000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (278, 'Stearne', 'McJerrow', 38, 'Male', '2023/04/03', 'Chennai', 75000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (279, 'Valentia', 'Landell', 29, 'Agender', '2012/04/22', 'Bangalore', 40000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (280, 'Garrick', 'Attenbrough', 32, 'Male', '1998/01/31', 'Ahmedabad', 45000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (281, 'Tootsie', 'Wisher', 55, 'Female', '2000/09/08', 'Delhi', 75000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (282, 'Hyacinth', 'Whittuck', 32, 'Female', '2000/09/11', 'Delhi', 60000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (283, 'Chicky', 'Southwick', 29, 'Female', '2008/01/18', 'Mumbai', 90000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (284, 'Cariotta', 'Castiello', 37, 'Female', '2006/10/28', 'Hyderabad', 65000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (285, 'Robby', 'Beresford', 43, 'Male', '1999/06/10', 'Surat', 50000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (286, 'Livvy', 'Avey', 31, 'Female', '1999/01/31', 'Bangalore', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (287, 'Eadmund', 'Peacher', 42, 'Male', '2013/10/18', 'Surat', 45000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (288, 'Kassia', 'Scryne', 45, 'Female', '2019/02/09', 'Mumbai', 75000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (289, 'Zerk', 'Tunnicliffe', 30, 'Male', '2006/04/21', 'Jaipur', 80000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (290, 'Anatola', 'Costley', 49, 'Female', '2022/11/11', 'Delhi', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (291, 'Finn', 'Kattenhorn', 51, 'Male', '1992/06/16', 'Chennai', 60000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (292, 'Lianne', 'Craine', 33, 'Female', '2011/06/13', 'Bangalore', 90000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (293, 'Kaylee', 'Choupin', 53, 'Female', '2006/03/04', 'Jaipur', 100000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (294, 'Skippie', 'Lamkin', 28, 'Male', '2004/01/31', 'Mumbai', 40000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (295, 'Allison', 'Stennet', 43, 'Female', '2015/07/17', 'Mumbai', 80000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (296, 'Selby', 'Allard', 49, 'Male', '1996/05/13', 'Kolkata', 50000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (297, 'Luis', 'Bevens', 37, 'Male', '2009/08/20', 'Bangalore', 65000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (298, 'Rudd', 'Rooze', 43, 'Male', '1992/08/21', 'Surat', 85000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (299, 'Tootsie', 'Crich', 42, 'Female', '2014/02/20', 'Bangalore', 40000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (300, 'Ailene', 'Dawtry', 55, 'Female', '2010/02/17', 'Ahmedabad', 45000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (301, 'Midge', 'Chaddock', 46, 'Female', '2007/01/30', 'Jaipur', 75000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (302, 'Ware', 'Ellings', 46, 'Male', '2000/12/02', 'Chennai', 90000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (303, 'Derk', 'Elacoate', 30, 'Male', '1998/02/23', 'Ahmedabad', 80000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (304, 'Ephrem', 'O''Doohaine', 30, 'Male', '2006/01/31', 'Mumbai', 100000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (305, 'Malanie', 'Spurway', 36, 'Female', '2017/04/21', 'Hyderabad', 40000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (306, 'Abigail', 'Bortoluzzi', 43, 'Female', '2015/07/12', 'Jaipur', 85000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (307, 'Adda', 'Eustes', 53, 'Female', '2007/07/04', 'Kolkata', 85000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (308, 'Jayme', 'Stegel', 48, 'Female', '2022/03/15', 'Ahmedabad', 70000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (309, 'Pepi', 'O''Dare', 41, 'Non-binary', '1993/09/22', 'Mumbai', 75000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (310, 'Trip', 'Gilhooley', 53, 'Male', '2005/04/23', 'Jaipur', 90000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (311, 'Nannette', 'Vian', 40, 'Bigender', '2000/11/02', 'Kolkata', 55000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (312, 'Sheffield', 'Guerry', 43, 'Genderfluid', '2015/11/20', 'Bangalore', 65000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (313, 'Clementine', 'Chesworth', 36, 'Female', '1993/05/17', 'Ahmedabad', 95000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (314, 'Lavena', 'Di Matteo', 49, 'Female', '2008/10/15', 'Kolkata', 95000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (315, 'Kerry', 'Barthot', 33, 'Female', '1994/03/25', 'Bangalore', 50000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (316, 'Thorsten', 'Krollman', 43, 'Male', '2009/11/18', 'Ahmedabad', 35000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (317, 'Jyoti', 'Hembrow', 52, 'Female', '2016/09/25', 'Ahmedabad', 100000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (318, 'Alden', 'Daniaud', 44, 'Male', '2014/12/16', 'Hyderabad', 80000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (319, 'Trixie', 'Levermore', 31, 'Female', '2001/01/02', 'Jaipur', 85000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (320, 'Anthony', 'Ubanks', 30, 'Male', '2018/08/29', 'Bangalore', 40000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (321, 'Estelle', 'Braidford', 45, 'Female', '1993/06/23', 'Pune', 85000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (322, 'Dorthea', 'Hunn', 52, 'Female', '1997/04/04', 'Bangalore', 85000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (323, 'Egbert', 'Holberry', 35, 'Male', '2019/12/30', 'Mumbai', 35000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (324, 'Biddy', 'Thomel', 44, 'Female', '2002/01/27', 'Delhi', 100000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (325, 'Jenifer', 'Harding', 49, 'Female', '2008/02/08', 'Delhi', 95000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (326, 'Bronny', 'Strowlger', 29, 'Male', '2010/10/20', 'Chennai', 90000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (327, 'Jordanna', 'Perree', 45, 'Genderqueer', '2018/03/01', 'Kolkata', 75000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (328, 'Shirline', 'Glenfield', 34, 'Non-binary', '2021/11/26', 'Ahmedabad', 95000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (329, 'Keenan', 'Cianelli', 31, 'Male', '2015/06/17', 'Kolkata', 95000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (330, 'Elnore', 'Silkstone', 38, 'Non-binary', '1999/03/21', 'Surat', 90000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (331, 'Demetris', 'Thornewell', 43, 'Female', '1992/06/22', 'Hyderabad', 60000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (332, 'Tully', 'Jochens', 28, 'Male', '2006/07/19', 'Hyderabad', 40000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (333, 'Andeee', 'Clarke-Williams', 45, 'Female', '2002/06/20', 'Hyderabad', 50000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (334, 'Connor', 'Cubbon', 55, 'Male', '2011/02/25', 'Bangalore', 35000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (335, 'Evangelina', 'Bernette', 50, 'Female', '1998/09/25', 'Surat', 55000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (336, 'Bevon', 'Croster', 49, 'Male', '2021/10/14', 'Surat', 35000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (337, 'Elsinore', 'Wolfers', 36, 'Female', '2002/12/17', 'Surat', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (338, 'Tye', 'Whitwell', 38, 'Male', '2004/04/26', 'Pune', 80000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (339, 'Loren', 'Ioannidis', 51, 'Female', '2011/12/19', 'Delhi', 95000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (340, 'Tobias', 'Hercules', 41, 'Male', '2015/02/13', 'Pune', 85000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (341, 'Raymond', 'Thayre', 54, 'Male', '2019/03/31', 'Mumbai', 50000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (342, 'Fairleigh', 'Goose', 52, 'Male', '2021/02/14', 'Chennai', 60000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (343, 'Damara', 'Mogey', 50, 'Female', '2009/05/16', 'Kolkata', 65000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (344, 'Kerri', 'Meeny', 51, 'Female', '2008/01/24', 'Hyderabad', 85000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (345, 'Ricki', 'Pontin', 37, 'Male', '2012/02/07', 'Delhi', 90000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (346, 'Horton', 'Sagg', 55, 'Male', '2010/06/01', 'Delhi', 40000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (347, 'Drona', 'Fellowes', 38, 'Female', '2015/01/13', 'Kolkata', 35000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (348, 'Zach', 'Ellaway', 34, 'Male', '1994/04/30', 'Pune', 85000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (349, 'Kingsly', 'Harrington', 46, 'Male', '2007/07/24', 'Delhi', 80000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (350, 'Casey', 'Caldera', 53, 'Female', '2012/02/29', 'Delhi', 70000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (351, 'Shepard', 'Gallier', 53, 'Male', '1999/12/25', 'Mumbai', 40000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (352, 'Paula', 'Casaletto', 29, 'Genderfluid', '1997/01/20', 'Delhi', 85000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (353, 'Elianora', 'Azam', 50, 'Female', '2020/12/11', 'Pune', 70000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (354, 'Rab', 'Brislan', 34, 'Male', '2002/02/16', 'Pune', 55000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (355, 'Carie', 'Gwyllt', 51, 'Female', '1998/07/04', 'Hyderabad', 40000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (356, 'Antonius', 'Edlin', 33, 'Male', '2000/07/28', 'Mumbai', 80000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (357, 'Hurley', 'Cayser', 50, 'Male', '2004/11/19', 'Kolkata', 40000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (358, 'Buck', 'Yurocjhin', 33, 'Male', '1996/12/11', 'Surat', 35000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (359, 'Patrice', 'Dignon', 54, 'Male', '2006/02/10', 'Bangalore', 45000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (360, 'Nissy', 'Eichmann', 31, 'Female', '1996/10/28', 'Mumbai', 90000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (361, 'Floria', 'Endacott', 42, 'Agender', '2008/06/20', 'Pune', 45000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (362, 'Katharina', 'Roggieri', 53, 'Female', '2012/04/20', 'Hyderabad', 100000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (363, 'Cullin', 'Lumby', 48, 'Male', '2004/09/30', 'Mumbai', 80000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (364, 'Haley', 'Winchcum', 33, 'Male', '2007/05/17', 'Kolkata', 55000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (365, 'Thom', 'Cormack', 30, 'Male', '1996/10/15', 'Bangalore', 75000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (366, 'Tirrell', 'Zanioletti', 42, 'Male', '2004/01/10', 'Jaipur', 40000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (367, 'Georas', 'Pruckner', 50, 'Male', '2008/09/29', 'Hyderabad', 45000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (368, 'Matthaeus', 'Dillingham', 38, 'Male', '1997/06/12', 'Pune', 85000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (369, 'Cyndia', 'Hebditch', 52, 'Female', '2012/08/10', 'Bangalore', 35000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (370, 'Franny', 'Pach', 50, 'Polygender', '2005/12/24', 'Chennai', 75000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (371, 'Margalit', 'Ternault', 37, 'Female', '2011/11/13', 'Pune', 75000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (372, 'Dermot', 'Tomanek', 43, 'Male', '2009/06/06', 'Bangalore', 60000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (373, 'Nevin', 'Wimsett', 35, 'Male', '2013/01/11', 'Hyderabad', 90000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (374, 'Gery', 'Favell', 33, 'Male', '2007/08/22', 'Ahmedabad', 100000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (375, 'Christopher', 'Manifold', 34, 'Male', '2017/10/13', 'Kolkata', 70000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (376, 'Arvin', 'Roder', 41, 'Male', '2005/11/08', 'Bangalore', 45000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (377, 'Gert', 'Valdes', 34, 'Female', '1994/10/16', 'Hyderabad', 35000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (378, 'Philippa', 'Bourner', 32, 'Female', '2000/08/23', 'Ahmedabad', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (379, 'Leonora', 'Danaher', 27, 'Female', '1995/10/04', 'Chennai', 90000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (380, 'Zared', 'Obell', 33, 'Polygender', '2019/01/19', 'Jaipur', 55000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (381, 'Mathe', 'Alanbrooke', 30, 'Male', '2014/05/05', 'Chennai', 75000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (382, 'Eve', 'Eshmade', 38, 'Female', '2014/03/19', 'Delhi', 95000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (383, 'Livia', 'Straker', 41, 'Female', '2004/05/11', 'Delhi', 95000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (384, 'Bailie', 'Moar', 50, 'Male', '2015/01/23', 'Hyderabad', 90000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (385, 'Fredia', 'Neal', 39, 'Female', '2017/03/28', 'Bangalore', 85000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (386, 'Efrem', 'Secker', 34, 'Male', '1995/01/06', 'Mumbai', 65000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (387, 'Debi', 'Ickeringill', 45, 'Female', '2011/12/12', 'Hyderabad', 75000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (388, 'Euphemia', 'Mille', 34, 'Female', '1992/12/07', 'Bangalore', 65000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (389, 'Micki', 'Leinweber', 51, 'Female', '1996/07/02', 'Mumbai', 55000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (390, 'Constantine', 'Meier', 43, 'Male', '1994/12/03', 'Bangalore', 40000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (391, 'Klement', 'Couroy', 32, 'Male', '2001/09/24', 'Pune', 60000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (392, 'Flory', 'Brookes', 28, 'Female', '2009/10/02', 'Chennai', 70000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (393, 'Gianni', 'Cutress', 36, 'Male', '2003/10/01', 'Jaipur', 100000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (394, 'Had', 'Jakoub', 39, 'Male', '1995/04/09', 'Kolkata', 100000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (395, 'Marsh', 'Ianni', 38, 'Male', '2008/12/23', 'Hyderabad', 45000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (396, 'Janna', 'Grinikhinov', 40, 'Female', '1996/12/31', 'Delhi', 70000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (397, 'Harrietta', 'Mariet', 27, 'Genderfluid', '2020/07/07', 'Pune', 55000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (398, 'Caria', 'Dahmel', 31, 'Genderqueer', '2020/10/11', 'Mumbai', 60000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (399, 'Maximilian', 'Spikeings', 54, 'Male', '2006/02/07', 'Ahmedabad', 75000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (400, 'Regine', 'Medendorp', 29, 'Non-binary', '2007/01/19', 'Jaipur', 45000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (401, 'Emelyne', 'Daunter', 41, 'Female', '2010/10/06', 'Pune', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (402, 'Fayth', 'Klees', 36, 'Polygender', '2023/01/30', 'Ahmedabad', 40000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (403, 'Wandis', 'Gierok', 50, 'Female', '2008/01/28', 'Jaipur', 35000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (404, 'Melloney', 'Wringe', 32, 'Female', '2015/02/02', 'Ahmedabad', 65000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (405, 'Rivkah', 'Nerney', 31, 'Female', '2009/12/23', 'Chennai', 55000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (406, 'Gonzales', 'Keneleyside', 35, 'Male', '2021/07/08', 'Surat', 35000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (407, 'Tabbie', 'Prescote', 40, 'Genderfluid', '2006/01/29', 'Chennai', 65000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (408, 'Eva', 'Bilofsky', 42, 'Female', '2002/02/25', 'Delhi', 60000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (409, 'Claiborne', 'Vatini', 39, 'Male', '2013/01/15', 'Kolkata', 60000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (410, 'Tarrah', 'Nuzzetti', 33, 'Female', '2008/12/01', 'Ahmedabad', 75000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (411, 'Curtis', 'Hubatsch', 45, 'Male', '2023/01/23', 'Delhi', 60000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (412, 'Ikey', 'Taylor', 36, 'Male', '1998/02/17', 'Jaipur', 95000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (413, 'Caye', 'Manson', 51, 'Genderqueer', '2008/07/11', 'Delhi', 40000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (414, 'Randall', 'Ianitti', 53, 'Male', '2010/12/21', 'Hyderabad', 80000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (415, 'Constanta', 'Dunderdale', 49, 'Female', '2019/11/30', 'Pune', 35000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (416, 'Ella', 'Guys', 53, 'Female', '2020/05/12', 'Surat', 65000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (417, 'Terrie', 'Fiddler', 28, 'Female', '1994/12/11', 'Surat', 95000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (418, 'Seka', 'Belamy', 44, 'Female', '2011/03/18', 'Jaipur', 60000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (419, 'Augustus', 'Scole', 50, 'Male', '2023/03/05', 'Ahmedabad', 35000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (420, 'Cody', 'Ranyard', 39, 'Female', '1996/07/14', 'Hyderabad', 80000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (421, 'Ynez', 'Glazebrook', 44, 'Female', '2009/07/23', 'Chennai', 70000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (422, 'Nathanael', 'Bompas', 35, 'Male', '2016/10/01', 'Kolkata', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (423, 'Drusy', 'Ormrod', 51, 'Female', '2004/05/28', 'Kolkata', 70000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (424, 'Truda', 'Gludor', 27, 'Female', '2002/04/29', 'Mumbai', 50000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (425, 'Sisely', 'Dimock', 50, 'Female', '1993/12/16', 'Mumbai', 35000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (426, 'Traver', 'Merkle', 40, 'Male', '1994/02/03', 'Chennai', 40000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (427, 'Carlie', 'MacLaughlin', 45, 'Female', '2003/12/01', 'Mumbai', 95000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (428, 'Dasie', 'Shakespeare', 34, 'Female', '1999/10/08', 'Surat', 80000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (429, 'Jaine', 'Persse', 31, 'Female', '2010/06/01', 'Bangalore', 60000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (430, 'Quintina', 'Beazley', 55, 'Female', '2003/01/10', 'Bangalore', 60000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (431, 'Owen', 'Vader', 51, 'Male', '2020/06/09', 'Chennai', 90000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (432, 'Kacy', 'But', 41, 'Female', '2020/05/08', 'Pune', 45000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (433, 'Kat', 'Ciobotaru', 43, 'Female', '2008/05/22', 'Chennai', 55000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (434, 'Archy', 'Roll', 44, 'Male', '2017/01/19', 'Surat', 95000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (435, 'Parker', 'Blaxall', 45, 'Male', '1992/05/21', 'Chennai', 50000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (436, 'Julianna', 'Claypole', 54, 'Female', '2017/11/24', 'Surat', 60000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (437, 'Robin', 'Craske', 37, 'Female', '1997/12/26', 'Ahmedabad', 75000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (438, 'Reynard', 'Harbor', 36, 'Male', '2013/07/30', 'Surat', 45000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (439, 'Sharity', 'Jeynes', 51, 'Female', '1996/03/12', 'Hyderabad', 40000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (440, 'Murdock', 'McFeate', 54, 'Male', '2004/06/28', 'Hyderabad', 45000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (441, 'Wendel', 'Norwich', 50, 'Male', '2010/01/30', 'Mumbai', 35000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (442, 'Jeanette', 'Turtle', 27, 'Female', '2003/01/24', 'Surat', 75000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (443, 'Caspar', 'Ciardo', 37, 'Male', '2000/12/25', 'Mumbai', 80000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (444, 'Torin', 'Whaites', 37, 'Male', '1996/01/18', 'Chennai', 35000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (445, 'Veradis', 'Pickrill', 33, 'Polygender', '2005/09/26', 'Surat', 45000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (446, 'Thedrick', 'Josipovitz', 39, 'Male', '2018/09/28', 'Chennai', 90000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (447, 'Cindelyn', 'D''Souza', 47, 'Female', '2007/05/03', 'Pune', 45000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (448, 'Janaye', 'Conville', 38, 'Female', '2000/08/30', 'Jaipur', 55000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (449, 'Anton', 'Dimitrov', 39, 'Male', '2007/07/11', 'Jaipur', 35000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (450, 'Marius', 'Toffoloni', 38, 'Male', '2005/10/11', 'Mumbai', 35000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (451, 'Theodoric', 'Lossman', 34, 'Male', '2007/04/02', 'Ahmedabad', 70000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (452, 'Eleni', 'Eglese', 42, 'Female', '2014/03/01', 'Ahmedabad', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (453, 'Itch', 'McClancy', 46, 'Male', '2011/03/04', 'Ahmedabad', 60000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (454, 'Kit', 'Patershall', 28, 'Male', '2000/12/28', 'Delhi', 55000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (455, 'Neille', 'Goodison', 31, 'Female', '2019/06/06', 'Delhi', 100000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (456, 'Idaline', 'Petel', 37, 'Female', '2000/11/24', 'Hyderabad', 60000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (457, 'Lilyan', 'Fontel', 28, 'Female', '2001/06/05', 'Hyderabad', 85000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (458, 'Hugh', 'Nattrass', 44, 'Male', '2023/03/28', 'Delhi', 100000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (459, 'Harv', 'Pollins', 34, 'Male', '1995/03/17', 'Mumbai', 65000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (460, 'Bessie', 'Pexton', 47, 'Female', '2007/12/22', 'Jaipur', 85000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (461, 'Ced', 'Joselovitch', 55, 'Male', '2004/05/02', 'Mumbai', 55000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (462, 'Andrew', 'Itscowics', 47, 'Male', '2007/06/16', 'Ahmedabad', 95000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (463, 'Chrissie', 'Alcalde', 27, 'Female', '2016/10/06', 'Pune', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (464, 'Dianemarie', 'Morphet', 31, 'Genderfluid', '1995/03/01', 'Jaipur', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (465, 'Philippe', 'Pauli', 39, 'Female', '2015/02/01', 'Kolkata', 45000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (466, 'Florida', 'Jewster', 33, 'Female', '2002/08/20', 'Pune', 50000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (467, 'Daniella', 'Skeemor', 45, 'Female', '1997/05/15', 'Chennai', 40000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (468, 'Hagan', 'Jurasz', 42, 'Male', '2014/02/18', 'Mumbai', 90000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (469, 'Denney', 'Niezen', 52, 'Male', '1998/03/03', 'Hyderabad', 70000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (470, 'Georgie', 'Castanos', 53, 'Female', '2012/06/25', 'Bangalore', 75000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (471, 'Evania', 'Saich', 55, 'Female', '1993/09/13', 'Surat', 100000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (472, 'Cristiano', 'Kerford', 33, 'Male', '2018/08/19', 'Jaipur', 50000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (473, 'Madelina', 'Bransom', 46, 'Female', '2023/06/06', 'Jaipur', 60000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (474, 'Merilee', 'Rodgier', 53, 'Female', '2012/12/18', 'Jaipur', 40000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (475, 'Kurt', 'Manterfield', 36, 'Male', '2008/08/12', 'Pune', 45000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (476, 'Farrel', 'Tumielli', 27, 'Male', '2010/10/01', 'Jaipur', 80000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (477, 'Sibley', 'Garnsey', 37, 'Female', '2020/04/22', 'Mumbai', 40000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (478, 'Constancy', 'Clymo', 33, 'Female', '1995/09/16', 'Mumbai', 55000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (479, 'Doti', 'Callaghan', 53, 'Female', '2019/03/28', 'Bangalore', 100000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (480, 'Kean', 'Twelvetree', 30, 'Male', '2014/06/21', 'Jaipur', 55000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (481, 'Willie', 'Tessington', 40, 'Female', '2007/07/19', 'Chennai', 60000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (482, 'Emmett', 'Varnals', 28, 'Polygender', '1995/08/08', 'Mumbai', 60000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (483, 'Lacey', 'Husk', 30, 'Female', '2008/02/13', 'Kolkata', 65000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (484, 'Bowie', 'Thurling', 34, 'Male', '2001/10/18', 'Ahmedabad', 70000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (485, 'Frederique', 'MacMenamin', 42, 'Female', '1994/05/08', 'Chennai', 70000, 'Sales');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (486, 'Durante', 'Trevett', 35, 'Male', '1997/01/28', 'Chennai', 85000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (487, 'Carlee', 'Baddow', 41, 'Female', '2013/06/01', 'Kolkata', 95000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (488, 'Loraine', 'Ahmad', 38, 'Female', '2013/11/29', 'Surat', 85000, 'Quality');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (489, 'Britni', 'Jude', 50, 'Female', '2020/09/20', 'Surat', 90000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (490, 'Geoffry', 'Tunkin', 34, 'Male', '2015/06/01', 'Mumbai', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (491, 'Jeanine', 'Largan', 44, 'Female', '2021/12/12', 'Bangalore', 35000, 'Production');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (492, 'Ophelia', 'Coughtrey', 52, 'Female', '2016/06/27', 'Kolkata', 65000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (493, 'Olympe', 'Cadney', 49, 'Female', '1992/09/26', 'Chennai', 60000, 'Marketing');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (494, 'Gregor', 'Beumant', 51, 'Male', '2000/11/24', 'Kolkata', 100000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (495, 'Kellia', 'Pinson', 33, 'Female', '1996/06/17', 'Kolkata', 45000, 'Administration');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (496, 'Randolf', 'Sleep', 31, 'Male', '2009/07/08', 'Kolkata', 100000, 'Accounts');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (497, 'Graig', 'Matfin', 54, 'Male', '2010/08/15', 'Pune', 100000, 'Research and Development');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (498, 'Linzy', 'Alton', 44, 'Female', '1998/11/13', 'Delhi', 90000, 'Information Technology');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (499, 'Claiborn', 'Gendricke', 47, 'Male', '2010/12/09', 'Ahmedabad', 55000, 'Human Resource Management');
insert into employees (id, first_name, last_name, age, gender, dob, city, salary, department) values (500, 'Sly', 'Galletley', 51, 'Male', '2022/11/20', 'Bangalore', 50000, 'Research and Development');
